# Generated by Django 4.2.29 on 2026-09-10 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '__first__'),
        ('institute', '0017_remove_educationboard_institute_educationboard_country_name_uniq_and_more'),
        ('accounts', '0018_user_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Tenant school this user belongs to. Platform Super Admins may have this blank.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.school'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_or_student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_users', to='institute.instituteprofile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='requested_role',
            field=models.CharField(choices=[('PLATFORM_SUPER_ADMIN', 'Platform Super Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('ACADEMIC_COORDINATOR', 'Academic Coordinator'), ('TEACHER', 'Teacher'), ('ACCOUNTANT', 'Accountant'), ('RECEPTIONIST', 'Receptionist'), ('TRANSPORT_MANAGER', 'Transport Manager'), ('LIBRARIAN', 'Librarian'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('subscriber', 'Subscriber'), ('student', 'Student (Legacy)'), ('teacher', 'Teacher (Legacy)'), ('editor', 'Editor (Legacy)'), ('academic_officer', 'Academic Officer (Legacy)'), ('admin', 'Admin (Legacy)')], default='SCHOOL_ADMIN', max_length=50),
        ),
    ]
