# Generated by Django on 2026-09-23 for PrimeSoul School ERP Three-Role Consolidation

from django.db import migrations, models


def migrate_users_to_three_canonical_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Group = apps.get_model('auth', 'Group')

    # Ensure canonical groups exist
    admin_group, _ = Group.objects.get_or_create(name='SCHOOL_ADMIN')
    student_group, _ = Group.objects.get_or_create(name='STUDENT')
    teacher_group, _ = Group.objects.get_or_create(name='TEACHER')

    for user in User.objects.all():
        role_raw = (user.requested_role or '').strip().upper()
        if role_raw in ('STUDENT', 'PARENT', 'GUARDIAN'):
            user.requested_role = 'STUDENT'
            user.is_staff = False
            target_group = student_group
        elif role_raw in ('TEACHER', 'FACULTY'):
            user.requested_role = 'TEACHER'
            user.is_staff = False
            target_group = teacher_group
        else:
            user.requested_role = 'SCHOOL_ADMIN'
            user.is_staff = True
            target_group = admin_group

        user.save(update_fields=['requested_role', 'is_staff'])
        user.groups.clear()
        user.groups.add(target_group)


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_school_alter_user_employee_or_student_id_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_users_to_three_canonical_roles,
            reverse_code=reverse_migration
        ),
        migrations.AlterField(
            model_name='user',
            name='requested_role',
            field=models.CharField(
                choices=[
                    ('SCHOOL_ADMIN', 'School Admin'),
                    ('STUDENT', 'Student'),
                    ('TEACHER', 'Teacher'),
                ],
                default='SCHOOL_ADMIN',
                max_length=50
            ),
        ),
    ]
