# Generated by Django 4.2.29 on 2026-09-10 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_teacher_institute'),
        ('tenants', '__first__'),
        ('academics', '0020_academicstream_academicyear_gradelevel_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0033_admissionstudent_gender_applying_class_admit_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('relationship_type', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian / Foster Parent')], default='Father', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('mobile_number', models.CharField(help_text='+91 E.164 phone number for WhatsApp / SMS alerts', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('parent_profile'), models.Model),
        ),
        migrations.CreateModel(
            name='StudentGuardianRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('relationship_type', models.CharField(default='Parent', max_length=50)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('can_pickup', models.BooleanField(default=True)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('student_guardian_relationship'), models.Model),
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['grade_level__display_order', 'section__name', 'roll_number']},
        ),
        migrations.AddField(
            model_name='student',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='12-digit Indian National Unique ID', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, db_index=True, help_text='School Admission / Scholar Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='apaar_id',
            field=models.CharField(blank=True, help_text='Automated Permanent Academic Account Registry (APAAR ID)', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('OBC', 'Other Backward Class (OBC-NCL)'), ('SC', 'Scheduled Caste (SC)'), ('ST', 'Scheduled Tribe (ST)'), ('EWS', 'Economically Weaker Section (EWS)')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='current_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.gradelevel'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Indian', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='pen_number',
            field=models.CharField(blank=True, help_text='Permanent Education Number (PEN) from Ministry of Education', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_tc_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, db_index=True, help_text='Class Roll Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Tenant school that owns this student record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='k12_students', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.section'),
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.academicstream'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='admission_policy_agreement',
            field=models.BooleanField(default=False, verbose_name='I have read and agree to the admission policy, fee structure, and rules of the institution.'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='admit_to_semester',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Legacy semester placement.', null=True),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='applying_for_class',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Class level (1-12) applying for.', null=True),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='choosen_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_students', to='academics.department'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='counseling_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselors', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='current_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='department_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='exam_name',
            field=models.CharField(blank=True, choices=[('CBSE_10', 'CBSE Class X'), ('CBSE_12', 'CBSE Class XII'), ('ICSE_10', 'ICSE Class X'), ('ISC_12', 'ISC Class XII'), ('STATE_10', 'State Board Class X'), ('STATE_12', 'State Board Class XII'), ('HSC', 'Higher Secondary Certificate (Legacy)'), ('SSC', 'Secondary School Certificate (Legacy)'), ('DAKHIL', 'Dakhil Exam (Legacy)'), ('VOCATIONAL', 'Vocational (Legacy)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=100, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender (Male/Female/Other).', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='guardian_mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=100, verbose_name="Mother's Name"),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/applicant/'),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='ssc_registration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='ssc_roll',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regularstudent',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.admissionstudent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'grade_level', 'section', 'roll_number'), name='unique_student_roll_per_section'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'admission_number'), name='unique_school_admission_number'),
        ),
        migrations.AddField(
            model_name='studentguardianrelationship',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relationships', to='students.parentprofile'),
        ),
        migrations.AddField(
            model_name='studentguardianrelationship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relationships', to='students.student'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profiles', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='studentguardianrelationship',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='unique_student_guardian'),
        ),
    ]
