# Generated by Django 4.2.29 on 2026-09-11 08:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0034_parentprofile_studentguardianrelationship_and_more'),
        ('tenants', '0001_initial'),
        ('academics', '0021_classteacherassignment_studentenrollment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='e.g. Periodic Test, Half Yearly, Annual Examination', max_length=100)),
                ('code', models.CharField(help_text='e.g. PT, HY, ANN, PRAC', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_types', to='tenants.school')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('assessment_type'), models.Model),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='e.g. Half Yearly Exam - Class 10', max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('weightage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Weightage percentage towards composite evaluation', max_digits=5)),
                ('ranking_enabled', models.BooleanField(default=True, help_text='Calculate student class and section ranks')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('FINALIZED', 'Finalized'), ('PUBLISHED', 'Published'), ('LOCKED', 'Locked')], default='DRAFT', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k12_exams', to='academics.academicyear')),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='examinations.assessmenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.gradelevel')),
            ],
            options={
                'ordering': ['-academic_year__start_date', 'grade_level__display_order', 'name'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('exam'), models.Model),
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=Decimal('33.00'), max_digits=6)),
                ('weightage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('is_optional', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='examinations.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configured_exam_subjects', to='tenants.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_instances', to='academics.subject')),
            ],
            options={
                'ordering': ['sequence_order', 'subject__name'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('exam_subject'), models.Model),
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='e.g. CBSE 8-Point Scale, ICSE Secondary Scale', max_length=100)),
                ('code', models.CharField(help_text='e.g. CBSE-8P, ICSE-STD', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use this scale by default for new exams')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='tenants.school')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('grade_scale'), models.Model),
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('NOT_ENTERED', 'Not Entered')], default='NOT_ENTERED', max_length=20)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_passed', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='academics.academicyear')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_marks', to='academics.studentenrollment')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_marks', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='examinations.exam')),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='examinations.examsubject')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__roll_number', 'student__first_name'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('student_mark'), models.Model),
        ),
        migrations.CreateModel(
            name='StudentExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('total_marks_obtained', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('total_max_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('overall_grade', models.CharField(blank=True, max_length=10)),
                ('overall_grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('result_status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('COMPARTMENT', 'Compartment / Eligible for Re-exam'), ('ABSENT', 'Absent in All Subjects'), ('WITHHELD', 'Result Withheld')], default='PASSED', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('FINALIZED', 'Finalized'), ('PUBLISHED', 'Published'), ('LOCKED', 'Locked')], default='DRAFT', max_length=20)),
                ('subjects_passed', models.PositiveIntegerField(default=0)),
                ('subjects_failed', models.PositiveIntegerField(default=0)),
                ('class_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('section_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_working_days', models.PositiveIntegerField(default=0)),
                ('attendance_present_days', models.PositiveIntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_remarks', models.TextField(blank=True)),
                ('principal_remarks', models.TextField(blank=True)),
                ('verification_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_results', to='academics.academicyear')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_results', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_results', to='academics.studentenrollment')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='examinations.exam')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_results', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_results', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_results', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_results', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
            ],
            options={
                'ordering': ['class_rank', '-percentage', 'student__roll_number'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('student_exam_result'), models.Model),
        ),
        migrations.CreateModel(
            name='MarksCorrectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('previous_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(help_text='Mandatory justification for mark correction')),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_corrections', to='examinations.exam')),
                ('mark_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='examinations.studentmark')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_correction_logs', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_corrections', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_corrections', to='academics.subject')),
            ],
            options={
                'ordering': ['-corrected_at'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('marks_correction_log'), models.Model),
        ),
        migrations.CreateModel(
            name='GradeScaleBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='e.g. A1, A2, B1, B2, C1, C2, D, E', max_length=10)),
                ('min_percentage', models.DecimalField(decimal_places=2, help_text='Lower percentage bound (inclusive)', max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, help_text='Upper percentage bound (inclusive)', max_digits=5)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 10.0, 9.0, 0.0', max_digits=4, null=True)),
                ('is_passing', models.BooleanField(default=True, help_text='Uncheck for failing grades (e.g. E / Below 33%)')),
                ('remarks', models.CharField(blank=True, help_text='e.g. Outstanding, Excellent, Good, Scope for Improvement', max_length=100)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='examinations.gradescale')),
            ],
            options={
                'ordering': ['-min_percentage'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('grade_scale_band'), models.Model),
        ),
        migrations.CreateModel(
            name='ExaminationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='e.g. Half Yearly Examinations 2026-27', max_length=100)),
                ('code', models.CharField(help_text='e.g. HYE-2026', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_sessions', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_sessions', to='tenants.school')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('examination_session'), models.Model),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_scale',
            field=models.ForeignKey(blank=True, help_text='Grading scale used for calculating subject and overall grades.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='examinations.gradescale'),
        ),
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k12_exams', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Optional. Leave blank to apply to all sections in this class.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='examinations.examinationsession'),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studentmark',
            index=models.Index(fields=['school', 'exam', 'student'], name='examination_school__4bd206_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmark',
            index=models.Index(fields=['exam_subject', 'student'], name='examination_exam_su_fa7f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmark',
            index=models.Index(fields=['exam', 'status'], name='examination_exam_id_a25a43_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentmark',
            constraint=models.UniqueConstraint(fields=('school', 'exam', 'exam_subject', 'student'), name='unique_student_exam_subject_mark'),
        ),
        migrations.AddIndex(
            model_name='studentexamresult',
            index=models.Index(fields=['school', 'exam', 'status'], name='examination_school__ba2f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamresult',
            index=models.Index(fields=['exam', 'percentage'], name='examination_exam_id_d0d332_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamresult',
            index=models.Index(fields=['verification_code'], name='examination_verific_105311_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentexamresult',
            constraint=models.UniqueConstraint(fields=('school', 'exam', 'student'), name='unique_student_exam_overall_result'),
        ),
        migrations.AddConstraint(
            model_name='gradescaleband',
            constraint=models.UniqueConstraint(fields=('scale', 'name'), name='unique_scale_band_name'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_school_grade_scale_code'),
        ),
        migrations.AddConstraint(
            model_name='examsubject',
            constraint=models.UniqueConstraint(fields=('exam', 'subject'), name='unique_exam_subject_configuration'),
        ),
        migrations.AddConstraint(
            model_name='examinationsession',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'code'), name='unique_school_academic_year_session_code'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('school', 'session', 'grade_level', 'section', 'name'), name='unique_exam_per_class_section'),
        ),
        migrations.AddConstraint(
            model_name='assessmenttype',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_school_assessment_type_code'),
        ),
    ]
