# Generated by Django 4.2.29 on 2026-09-11 10:41

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('academics', '0021_classteacherassignment_studentenrollment_and_more'),
        ('students', '0034_parentprofile_studentguardianrelationship_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='e.g. North City Route 1, Rohini to DPS RKP', max_length=150)),
                ('code', models.CharField(help_text='e.g. R-01, ROUTE-NORTH', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Route coverage areas and key arterial roads')),
                ('fare', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard monthly transport fee for this route (₹)', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='tenants.school')),
            ],
            options={
                'ordering': ['code', 'name'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('transport_route'), models.Model),
        ),
        migrations.CreateModel(
            name='TransportStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Full legal name', max_length=150)),
                ('phone', models.CharField(help_text='10-digit Indian contact mobile number', max_length=20)),
                ('role', models.CharField(choices=[('DRIVER', 'Bus / Van Driver'), ('ATTENDANT', 'Attendant / Bus Helper')], default='DRIVER', max_length=20)),
                ('license_number', models.CharField(blank=True, help_text='Commercial Driving License number (Mandatory for Drivers)', max_length=50)),
                ('license_expiry', models.DateField(blank=True, help_text='Driving License expiration date', null=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_staff', to='tenants.school')),
                ('user', models.ForeignKey(blank=True, help_text='Optional User account if driver logs into ERP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'name'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('transport_staff'), models.Model),
        ),
        migrations.CreateModel(
            name='TransportVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('vehicle_number', models.CharField(help_text='Institutional identifier (e.g. BUS-01, VAN-03)', max_length=50)),
                ('registration_number', models.CharField(help_text='RTO Registration number (e.g. DL-01-AB-1234, MH-02-CD-5678)', max_length=50)),
                ('vehicle_type', models.CharField(choices=[('BUS', 'Full Size School Bus'), ('MINI_BUS', 'Mini Bus'), ('VAN', 'School Van / Winger'), ('CAB', 'Cab / Car'), ('OTHER', 'Other Transport Vehicle')], default='BUS', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=40, help_text='Permissible seating capacity')),
                ('is_active', models.BooleanField(default=True)),
                ('insurance_expiry', models.DateField(blank=True, help_text='Vehicle commercial insurance expiry date', null=True)),
                ('pollution_cert_expiry', models.DateField(blank=True, help_text='PUCC validity expiry date', null=True)),
                ('fitness_cert_expiry', models.DateField(blank=True, help_text='RTO Fitness certificate expiry date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Maintenance history, GPS vendor, or contractor notes')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_vehicles', to='tenants.school')),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('transport_vehicle'), models.Model),
        ),
        migrations.CreateModel(
            name='VehicleRouteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_route_assignments', to='academics.academicyear')),
                ('attendant', models.ForeignKey(blank=True, limit_choices_to={'role': 'ATTENDANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendant_route_assignments', to='transport.transportstaff')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'DRIVER'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_route_assignments', to='transport.transportstaff')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='transport.transportroute')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_route_assignments', to='tenants.school')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to='transport.transportvehicle')),
            ],
            options={
                'ordering': ['route__code'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('vehicle_route_assignment'), models.Model),
        ),
        migrations.CreateModel(
            name='TransportStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='e.g. Rohini West Metro Station, Gate 2', max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('sequence', models.PositiveSmallIntegerField(default=1, help_text='Stop order along route (1, 2, 3...)')),
                ('pickup_time', models.TimeField(blank=True, help_text='Morning pickup timing', null=True)),
                ('drop_time', models.TimeField(blank=True, help_text='Afternoon drop-off timing', null=True)),
                ('fare', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stop-specific monthly fare override (₹), 0 to inherit route standard fare', max_digits=8)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.transportroute')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_stops', to='tenants.school')),
            ],
            options={
                'ordering': ['route', 'sequence'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('transport_stop'), models.Model),
        ),
        migrations.CreateModel(
            name='StudentTransportAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('transport_status', models.CharField(choices=[('ACTIVE', 'Active Transport User'), ('INACTIVE', 'Inactive / Cancelled'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Medical notes, parent pickup authorization, etc.')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_transport_assignments', to='academics.academicyear')),
                ('drop_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_student_assignments', to='transport.transportstop')),
                ('pickup_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_student_assignments', to='transport.transportstop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_transport_assignments', to='transport.transportroute')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_transport_assignments', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='students.student')),
            ],
            options={
                'ordering': ['student__first_name', 'student__last_name'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('student_transport_assignment'), models.Model),
        ),
        migrations.AddConstraint(
            model_name='transportvehicle',
            constraint=models.UniqueConstraint(fields=('school', 'vehicle_number'), name='unique_school_transport_vehicle_number'),
        ),
        migrations.AddConstraint(
            model_name='transportstop',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='unique_route_stop_sequence'),
        ),
        migrations.AddConstraint(
            model_name='transportroute',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'code'), name='unique_school_academic_route_code'),
        ),
        migrations.AddConstraint(
            model_name='studenttransportassignment',
            constraint=models.UniqueConstraint(fields=('academic_year', 'student'), name='unique_academic_student_transport'),
        ),
    ]
