# Generated by Django 4.2.29 on 2026-09-15 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0034_parentprofile_studentguardianrelationship_and_more'),
        ('academics', '0021_classteacherassignment_studentenrollment_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('application_number', models.CharField(db_index=True, max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('category', models.CharField(default='General', max_length=50)),
                ('aadhaar_number', models.CharField(blank=True, help_text='12-digit Indian National Identity', max_length=20)),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('previous_school_tc_number', models.CharField(blank=True, max_length=100)),
                ('previous_grade', models.CharField(blank=True, max_length=50)),
                ('previous_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('father_mobile', models.CharField(blank=True, max_length=20)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_aadhaar', models.CharField(blank=True, max_length=20)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('mother_mobile', models.CharField(blank=True, max_length=20)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_aadhaar', models.CharField(blank=True, max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_mobile', models.CharField(blank=True, max_length=20)),
                ('guardian_relation', models.CharField(blank=True, max_length=50)),
                ('current_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview / Assessment Scheduled'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted'), ('ADMITTED', 'Admitted / Enrolled'), ('WITHDRAWN', 'Withdrawn by Parent')], default='DRAFT', max_length=20)),
                ('application_fee_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], default='NOT_REQUIRED', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('admission_application'), models.Model),
        ),
        migrations.CreateModel(
            name='AdmissionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='e.g. Academic Session 2026-27 Admissions', max_length=150)),
                ('application_start', models.DateField()),
                ('application_end', models.DateField()),
                ('admission_start', models.DateField()),
                ('admission_end', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for Applications'), ('CLOSED', 'Applications Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('application_number_prefix', models.CharField(default='APP-2026', max_length=20)),
                ('admission_number_prefix', models.CharField(default='ADM-2026', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_sessions', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_sessions', to='tenants.school')),
            ],
            options={
                'ordering': ['-academic_year__start_date', '-created'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('admission_session'), models.Model),
        ),
        migrations.CreateModel(
            name='AdmissionInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('scheduled_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='Admissions Office', max_length=200)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'Applicant No Show')], default='SCHEDULED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='admissions.admissionapplication')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_interviews', to='tenants.school')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('admission_interview'), models.Model),
        ),
        migrations.CreateModel(
            name='AdmissionEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('enquiry_number', models.CharField(db_index=True, max_length=50)),
                ('student_name', models.CharField(max_length=150)),
                ('parent_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(help_text='10-digit Indian mobile number', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('WALK_IN', 'Walk-In / Campus Visit'), ('WEBSITE', 'Website Online Enquiry'), ('PHONE', 'Telephone Enquiry'), ('REFERRAL', 'Parent / Staff Referral'), ('SOCIAL_MEDIA', 'Social Media Campaign'), ('OTHER', 'Other')], default='WALK_IN', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New Enquiry'), ('CONTACTED', 'Contacted'), ('FOLLOW_UP', 'Follow-up Scheduled'), ('CONVERTED', 'Converted to Application'), ('LOST', 'Lost / Not Interested'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('admission_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='admissions.admissionsession')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('interested_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='academics.gradelevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_enquiries', to='tenants.school')),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('admission_enquiry'), models.Model),
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('transfer_certificate', 'Transfer Certificate (TC)'), ('previous_school_certificate', 'Previous School Report Card / Marksheet'), ('address_proof', 'Address Proof (Aadhaar / Utility Bill)'), ('student_photo', 'Student Passport Photograph'), ('parent_id', 'Parent Identity Proof'), ('academic_document', 'Academic Document / Certificate'), ('other', 'Other Supporting Document')], default='other', max_length=50)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(upload_to='admissions/documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified & Approved'), ('REJECTED', 'Rejected / Re-upload Required')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.admissionapplication')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_documents', to='tenants.school')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_admission_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('admission_document'), models.Model),
        ),
        migrations.CreateModel(
            name='AdmissionClassConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('total_seats', models.PositiveIntegerField(default=40)),
                ('reserved_seats', models.PositiveIntegerField(default=0, help_text='RTE / Quota / Staff ward reserved seats')),
                ('application_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('admission_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_configs', to='admissions.admissionsession')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_configs', to='academics.gradelevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_class_configs', to='tenants.school')),
            ],
            options={
                'ordering': ['grade_level__display_order'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('admission_class_config'), models.Model),
        ),
        migrations.CreateModel(
            name='AdmissionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('subject', models.CharField(max_length=100)),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='admissions.admissionapplication')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_assessments', to='tenants.school')),
            ],
            options={
                'ordering': ['subject'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('admission_assessment'), models.Model),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='admission_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.admissionsession'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='admitted_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_application', to='students.student'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='admissions.admissionenquiry'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='requested_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to='academics.gradelevel'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='requested_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_applications', to='academics.academicstream'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to='tenants.school'),
        ),
        migrations.AddConstraint(
            model_name='admissionsession',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_school_admission_session_name'),
        ),
        migrations.AddConstraint(
            model_name='admissionenquiry',
            constraint=models.UniqueConstraint(fields=('school', 'enquiry_number'), name='unique_school_enquiry_number'),
        ),
        migrations.AddConstraint(
            model_name='admissionclassconfig',
            constraint=models.UniqueConstraint(fields=('school', 'admission_session', 'grade_level'), name='unique_session_grade_seat_config'),
        ),
        migrations.AddConstraint(
            model_name='admissionapplication',
            constraint=models.UniqueConstraint(fields=('school', 'admission_session', 'application_number'), name='unique_school_session_app_num'),
        ),
    ]
