# Generated by Django 4.2.29 on 2026-09-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0016_instituteprofile_curriculum'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='educationboard',
            name='institute_educationboard_country_name_uniq',
        ),
        migrations.AlterUniqueTogether(
            name='educationboard',
            unique_together={('country', 'name')},
        ),
    ]
