# Generated by Django 4.2.29 on 2026-09-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0017_remove_educationboard_institute_educationboard_country_name_uniq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteprofile',
            name='institute_type',
            field=models.CharField(blank=True, choices=[('school', 'School (CBSE / ICSE / State Board)'), ('madrasah', 'Madrasah (e.g. Dakhil, Alim, Fazil)'), ('polytechnic', 'Polytechnic Institute')], help_text='Determines terminology (Department vs Group) and admission/counselling flow.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='instituteprofile',
            name='site_header',
            field=models.CharField(default='PrimeSoul School ERP', help_text='Will be displayed in SuperAdmin Dashboard', max_length=100),
        ),
        migrations.AlterField(
            model_name='instituteprofile',
            name='site_title',
            field=models.CharField(default='Welcome to PrimeSoul School ERP', help_text='Title of the application/site', max_length=100),
        ),
        migrations.AlterField(
            model_name='instituteprofile',
            name='super_admin_index_title',
            field=models.CharField(default='PrimeSoul School ERP Admin', help_text='Will be displayed in SuperAdmin dashboard listing pages', max_length=100),
        ),
    ]
