# Generated by Django 4.2.29 on 2026-09-11 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0007_alter_teacher_options_designation_school_and_more'),
        ('academics', '0021_classteacherassignment_studentenrollment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='e.g. Room 101, Physics Lab, Senior Computer Lab', max_length=100)),
                ('room_number', models.CharField(help_text='e.g. 101, LAB-02, AUD', max_length=30)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'General Classroom'), ('LAB', 'Science / Computer Lab'), ('LIBRARY', 'Library Room'), ('AUDITORIUM', 'Auditorium / Multipurpose Hall'), ('ACTIVITY', 'Sports / Music / Activity Hall'), ('OTHER', 'Other Special Facility')], default='CLASSROOM', max_length=30)),
                ('capacity', models.PositiveIntegerField(default=40, help_text='Seating capacity')),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='tenants.school')),
            ],
            options={
                'ordering': ['room_number', 'name'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('classroom'), models.Model),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='e.g. Period 1, Assembly, Morning Break, Period 6', max_length=100)),
                ('period_number', models.PositiveSmallIntegerField(blank=True, help_text='Sequential academic period index (null for breaks, assemblies, etc.)', null=True)),
                ('start_time', models.TimeField(help_text='Slot start time (HH:MM)')),
                ('end_time', models.TimeField(help_text='Slot end time (HH:MM)')),
                ('is_break', models.BooleanField(default=False, help_text='Designates non-instructional slots (Recess, Lunch, Break)')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='tenants.school')),
            ],
            options={
                'ordering': ['display_order', 'start_time'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('time_slot'), models.Model),
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('day_name', models.CharField(blank=True, max_length=20)),
                ('is_working', models.BooleanField(default=True, help_text='Uncheck for weekends or non-working days.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='tenants.school')),
            ],
            options={
                'ordering': ['display_order', 'weekday'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('working_day'), models.Model),
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('entry_type', models.CharField(choices=[('CLASS', 'Regular Class'), ('LAB', 'Practical / Lab'), ('ACTIVITY', 'Co-Curricular / Activity'), ('BREAK', 'Scheduled Break'), ('FREE', 'Self Study / Free Period')], default='CLASS', max_length=20)),
                ('notes', models.CharField(blank=True, help_text='Optional remarks or lesson topic', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='timetable.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='tenants.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.section')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='teachers.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timeslot')),
                ('working_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.workingday')),
            ],
            options={
                'ordering': ['working_day__display_order', 'time_slot__display_order', 'time_slot__start_time'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('timetable_entry'), models.Model),
        ),
        migrations.AddConstraint(
            model_name='workingday',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'weekday'), name='unique_school_academic_working_day'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['school', 'academic_year', 'working_day', 'time_slot'], name='timetable_t_school__ac281f_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['teacher', 'working_day', 'time_slot'], name='timetable_t_teacher_5e4480_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['section', 'working_day', 'time_slot'], name='timetable_t_section_7c13aa_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['room', 'working_day', 'time_slot'], name='timetable_t_room_id_e04ccc_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'name'), name='unique_school_academic_time_slot_name'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('school', 'room_number'), name='unique_school_room_number'),
        ),
    ]
