# Generated by Django 4.2.29 on 2026-09-10 06:37

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('academics', '0020_academicstream_academicyear_gradelevel_section_and_more'),
        ('students', '0034_parentprofile_studentguardianrelationship_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConcession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Sibling Concession 20%', max_length=150)),
                ('concession_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED_AMOUNT', 'Fixed Amount (₹)'), ('FULL_WAIVER', '100% Full Waiver')], default='PERCENTAGE', max_length=30)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage value (e.g. 20.00) or fixed amount in INR (e.g. 5000.00)', max_digits=12)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional ceiling cap for percentage concessions in INR', max_digits=12, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('approval_required', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Tuition Fee', max_length=150)),
                ('code', models.CharField(help_text='e.g. TUITION, ANNUAL, TRANSPORT', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('TUITION', 'Tuition Fee'), ('ADMISSION', 'Admission Fee'), ('ANNUAL', 'Annual Charges'), ('DEVELOPMENT', 'Development Fee'), ('COMPUTER', 'Computer / IT Fee'), ('LAB', 'Science / Lab Fee'), ('ACTIVITY', 'Sports & Activity Fee'), ('EXAM', 'Examination Fee'), ('TRANSPORT', 'Transport / Bus Fee'), ('LIBRARY', 'Library Fee'), ('HOSTEL', 'Hostel Fee'), ('OTHER', 'Other / Miscellaneous')], default='TUITION', max_length=50)),
                ('is_recurring', models.BooleanField(default=True, help_text='True if charged on recurring intervals')),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(help_text='Tenant school that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_name', models.CharField(help_text='e.g. Q1 (Apr-Jun 2026), July 2026', max_length=150)),
                ('due_date', models.DateField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concession_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_installments', to='academics.academicyear')),
            ],
            options={
                'ordering': ['due_date', 'student'],
            },
        ),
        migrations.CreateModel(
            name='FeeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=100)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concession', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_invoices', to='academics.academicyear')),
                ('school', models.ForeignKey(help_text='Tenant school that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='students.student')),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Class 10 Standard Fee 2026-27', max_length=150)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly (Q1, Q2, Q3, Q4)'), ('HALF_YEARLY', 'Half-Yearly'), ('ANNUAL', 'Annual (One-Time)'), ('CUSTOM', 'Custom Frequency')], default='QUARTERLY', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.academicyear')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.gradelevel')),
                ('school', models.ForeignKey(help_text='Tenant school that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
            ],
            options={
                'ordering': ['academic_year', 'grade_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_concession_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional custom one-off concession amount in INR', max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXEMPTED', 'Exempted')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_assignments', to='academics.academicyear')),
                ('concession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='fees.feeconcession')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to='fees.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique Gateway ID, Cheque Ref, or Cash Voucher ID', max_length=100)),
                ('gateway', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque / Demand Draft'), ('UPI', 'UPI Manual / Static QR'), ('CARD', 'Debit / Credit Card (POS)'), ('NET_BANKING', 'Net Banking / NEFT / RTGS'), ('RAZORPAY', 'Razorpay Payment Gateway'), ('OTHER', 'Other Gateway / Mode')], default='CASH', max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending / Processing'), ('SUCCESS', 'Success / Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=30)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cheque_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('clearance_status', models.CharField(blank=True, choices=[('PENDING', 'Pending Clearance'), ('CLEARED', 'Cleared / Realized'), ('BOUNCED', 'Bounced / Returned')], default='PENDING', max_length=30)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='fees.feeinvoice')),
                ('school', models.ForeignKey(help_text='Tenant school that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='students.student')),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='fees.feeinstallment')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='fees.feeinvoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='fees.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in INR', max_digits=12)),
                ('mandatory', models.BooleanField(default=True)),
                ('due_day', models.PositiveSmallIntegerField(default=10, help_text='Day of month on which installment is due (e.g. 10th)')),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_items', to='fees.feehead')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feestructure')),
            ],
        ),
        migrations.CreateModel(
            name='FeeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=50)),
                ('receipt_date', models.DateField()),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='fees/receipts/')),
                ('qr_verification_code', models.CharField(blank=True, max_length=255)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='fees.paymenttransaction')),
                ('school', models.ForeignKey(help_text='Tenant school that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_receipts', to='students.student')),
            ],
            options={
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='feeinstallment',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='fees.feestructure'),
        ),
        migrations.AddField(
            model_name='feeinstallment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_installments', to='students.student'),
        ),
        migrations.AddField(
            model_name='feeconcession',
            name='applicable_fee_heads',
            field=models.ManyToManyField(blank=True, help_text='Specific fee heads eligible for this concession. If empty, applies to Tuition Fee by default.', related_name='concessions', to='fees.feehead'),
        ),
        migrations.AddField(
            model_name='feeconcession',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_concessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeconcession',
            name='school',
            field=models.ForeignKey(help_text='Tenant school that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.school'),
        ),
        migrations.CreateModel(
            name='FeeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. INVOICE_CREATED, PAYMENT_RECEIVED, CHEQUE_BOUNCED', max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_audit_logs', to='tenants.school')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentfeeassignment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'fee_structure'), name='unique_student_year_fee_structure'),
        ),
        migrations.AddConstraint(
            model_name='feestructureitem',
            constraint=models.UniqueConstraint(fields=('fee_structure', 'fee_head'), name='unique_structure_fee_head'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'grade_level', 'name'), name='unique_school_grade_fee_structure'),
        ),
        migrations.AddConstraint(
            model_name='feereceipt',
            constraint=models.UniqueConstraint(fields=('school', 'receipt_number'), name='unique_school_receipt_number'),
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.UniqueConstraint(fields=('school', 'invoice_number'), name='unique_school_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='feehead',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_school_fee_head_code'),
        ),
    ]
