# Generated by Django 4.2.29 on 2026-09-10 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0006_teacher_institute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='designation',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_teachers', to='tenants.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('employee_code', models.CharField(blank=True, db_index=True, help_text='Institutional Employee / Staff ID', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('department_wing', models.CharField(blank=True, help_text='Academic wing (e.g. Primary, Middle, Secondary, Senior Secondary)', max_length=100)),
                ('qualification', models.CharField(blank=True, help_text='Highest educational degrees (e.g. M.Sc Mathematics, B.Ed, CTET)', max_length=255)),
                ('specialization', models.CharField(blank=True, help_text='Primary subjects / specialization area', max_length=255)),
                ('joining_date', models.DateField(blank=True, help_text='Date of joining the institution', null=True)),
                ('mobile_number', models.CharField(blank=True, help_text='+91 E.164 contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profiles', to='teachers.designation')),
                ('school', models.ForeignKey(blank=True, help_text='Tenant school where this teacher is employed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profiles', to='tenants.school')),
                ('user', models.OneToOneField(help_text='User account associated with this teacher', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('teacher_profile'), models.Model),
        ),
    ]
