# Generated by Django 4.2.29 on 2026-09-10 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full legal name of the school / institution', max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe unique identifier', max_length=100, unique=True)),
                ('subdomain', models.CharField(db_index=True, help_text='Subdomain prefix (e.g. dpsdelhi)', max_length=100, unique=True)),
                ('custom_domain', models.CharField(blank=True, help_text='Optional custom domain (e.g. dpsdelhi.edu.in)', max_length=255, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='tenants/favicons/')),
                ('board', models.CharField(choices=[('CBSE', 'Central Board of Secondary Education (CBSE)'), ('ICSE', 'Council for the Indian School Certificate Examinations (ICSE/ISC)'), ('STATE', 'State Board of Secondary Education'), ('IB', 'International Baccalaureate (IB)'), ('CAMBRIDGE', 'Cambridge Assessment International Education (IGCSE)'), ('OTHER', 'Other / Independent Board')], default='CBSE', max_length=50)),
                ('affiliation_number', models.CharField(blank=True, help_text='CBSE / ICSE / State Board Affiliation Number', max_length=100)),
                ('school_code', models.CharField(blank=True, help_text='Official Board School Code', max_length=50)),
                ('udise_code', models.CharField(blank=True, help_text='Unified District Information System for Education (UDISE+) Code', max_length=50)),
                ('recognition_number', models.CharField(blank=True, help_text='State Department Recognition / Registration Number', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Enables or disables access for this entire school tenant')),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Standard Plan', max_length=100)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('max_students', models.PositiveIntegerField(default=1000)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.school')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.school')),
            ],
            options={
                'ordering': ['-is_primary', 'domain'],
            },
        ),
    ]
